User & user info DB, backend apis
Toblerone0629/Employee-Management-System pull request #6
Opened 2024-01-20 13:28 UTC by Toblerone0629

- Create Database tables
    - User
    - personal_info
    - Role
    - Address
    - Contact
- Create user && auth routers
- Modify duplicate or similar logic to **services** folder
- Implement user & user info, auth APIs
    - user
        - getAllUsers (for all employees page)
        - getUserById (for user detail page)
        - delete (only set deleted to true, will still keep the data)
    - user info (personal_info)
        - create
        - update
        - both could create/update the whole table at once
    - auth
        - login
        - signup

2024-01-21 06:47 UTC, DDDDDeng2022 commented on server/db/models/personalInfo.js
> +    ssn: {
还需要添加ssn的start date和end date

2024-01-21 06:57 UTC, DDDDDeng2022 requested changes
先加ssn的开始时间和结束时间再重新更新一下pr吧

2024-01-21 06:57 UTC, DDDDDeng2022 commented on server/db/models/personalInfo.js
> +                return value.includes("@");
后端其实不用再进行一遍邮箱的验证，前端form会先验证，合法的情况下才能成功提交

2024-01-22 00:41 UTC, Toblerone0629 commented on server/db/models/personalInfo.js
> +    ssn: {
看了一遍文档，目前没有看到有需要start date和end date的地方

2024-01-22 00:42 UTC, Toblerone0629 commented on server/db/models/personalInfo.js
> +                return value.includes("@");
前端和后端都有validation的情况才可以cover大部分的corner error case

2024-01-22 02:34 UTC, DDDDDeng2022 approved these changes

2024-01-22 02:34 UTC, merged